kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-mon-custom-role-bind-all
subjects:
  - kind: Group
    name: system:serviceaccount:prometheus
roleRef:
  kind: ClusterRole
  name: prometheus-mon-custom-role
  apiGroup: rbac.authorization.k8s.io

